version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo-db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-username
      - MONGO_INITDB_ROOT_PASSWORD=admin-pass
      - MONGO_INITDB_DATABASE=admin
    ports: 
      - '27017:27017'
    volumes:
      - ./mongodb_data_container:/data/db
  mongo-express:
    image: 'mongo-express'
    ports: 
      - '8081:8081'
    container_name: 'mongo-db-client'
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin-username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin-pass
  postgresql:
    image: postgres:latest
    container_name: postgresql-db
    environment:
      - POSTGRES_USER=admin-username
      - POSTGRES_PASSWORD=admin-username
      - POSTGRES_DB=admin
    ports:
      - '5433:5432'
    volumes:
      - ./postgresql_db_data:/var/lib/postgresql/data/
